### ISSUE TITLE
Scores not saving?

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#579] opened 2020-03-29 01:16 UTC
needs testing

**Comment by ClobberXD** [comment] 2020-04-24 05:15
This was reported by a couple of players yesterday. Adding to the milestone.

**Comment by ClobberXD** [comment] 2020-04-25 06:00
I'm unable to reproduce this. I tested by (1) only capturing the flag (2) only killing an enemy, and (3) both. My rankings went up each and every single time. I suspect there's a very specific way in which this bug can be reproduced.

**Comment by rubenwardy** [comment] 2020-04-25 13:55
Have you tried guns and rockets?

**Comment by ClobberXD** [comment] 2020-04-25 20:05
I haven't tried guns and rockets, but I doubt they're going to make a difference. I'll check.

**Comment by rubenwardy** [comment] 2020-04-25 20:19
I got a report from a player about this via pm, may have been before the stats rewrites idk

**Comment by ClobberXD** [comment] 2020-04-26 02:06
A certain player was still reporting this issue two days ago. But no one else seems to have encountered this issue.

**Comment by ClobberXD** [comment] 2020-04-26 02:15
There's been a bunch of commits to `ctf_stats/init.lua`. Let's hope this got fixed automatically.

**Comment by rubenwardy** [comment] 2020-04-26 02:31
> There's been a bunch of commits to `ctf_stats/init.lua`. Let's hope this got fixed automatically.

That's both my favourite and least favourite type of fix

**Comment by ClobberXD** [comment] 2020-04-26 08:16
Tried using guns as well, still couldn't reproduce anything.

What I'm thinking is that the player in question (probably one single player) got a huge amount of points within around 10 seconds, but the server probably crashed before the data is saved to disk (once every 13s IIRC), which means they lost the score from that streak.

**Comment by rubenwardy** [comment] 2020-04-29 11:54
User splash_dark claimed that they lost score when the server crash. I can see from the logs that they had gained score today, but their current score is 0. I can't see any /reset_rankings (it may not be logged correctly?)

**Comment by ClobberXD** [comment] 2020-04-29 14:49
https://github.com/MT-CTF/capturetheflag/blob/904a2869fd34a56d833707dd97d0b35ae6210b99/mods/ctf/ctf_stats/chat.lua#L162-L169

If `/reset_rankings` was executed, it should be logged

**Comment by ClobberXD** [comment] 2020-04-30 18:43
Can reproduce every single time with the following steps:

- Create new singleplayer world. Join the world.
- Capture the flag (match duration doesn't seem to matter)
- After being shown the match summary, re-log.
- Type /r; notice all the stats are empty.
- Type /s, click on "<< Previous match"; notice clearly having scored (at least) 70 points for the attempt+capture.

**Comment by ClobberXD** [comment] 2020-05-01 15:32
What was I saying. There's no guarantee that the stats I lost was because of this bug. It could also be due to the fact that I shut down the server before it saves the stats to mod storage. This is certainly not the same as this issue, where players gain thousands of points over multiple hours and all the points are gone when the server crashes.

One thing we can do is to save stats to mod storage at the end of a match. This is not going to *directly* fix the bug in question (AFAIK), but it'd at least eliminate other causes and make the troubleshooting more straightforward.

**Comment by Thomas--S** [comment] 2020-05-07 18:55
I'll reopen this, as this was most likely closed by mistake by using the phrase `isn't going to fix #...` in the other PR.

**Comment by ClobberXD** [comment] 2020-05-07 19:38
Oh, oops. Sorry. :)

**Comment by Panquesito7** [comment] 2020-05-07 21:19
> all the points are gone when the server crashes

AFAIK, this is because **almost** each time a player leaves, their scores are reset.

**Comment by ClobberXD** [comment] 2020-05-08 12:12
> AFAIK, this is because **almost** each time a player leaves, their scores are reset.

This is interesting. Are you sure this is exactly what happens? Have you observed this more than once? Would you be able to quantify "almost"?

**Comment by Panquesito7** [comment] 2020-05-08 18:29
> Are you sure this is exactly what happens?

It seems their points are being reset after the server crashes.

**Comment by ClobberXD** [comment] 2020-05-09 01:50
> It seems their points are being reset after the server crashes.

Yes, that's what we were already suspecting. So I'm guessing the scores aren't reset when the player leaves as well?

**Comment by ClobberXD** [comment] 2020-05-13 14:25
Seems to be fixed by #608, although I'd prefer to keep this open until the root cause is found and fixed.

**Comment by ClobberXD** [comment] 2020-05-30 09:58
Removing this bug from the milestone...

**Closed** 2021-11-30 01:17 UTC
Labels: Bug / Bugfix, :gear: Scoring
