### ISSUE TITLE
ERROR[Emerge-0]: NodeResolver: failed to resolve node name 'fireflies:hidden_firefly'

### ISSUE THREAD

**Issue by eliam** [MT-CTF/capturetheflag#664] opened 2020-06-13 13:16 UTC
Based on version from: https://content.minetest.net/packages/rubenwardy/capturetheflag/

**Comment by ClobberXD** [comment] 2020-06-13 15:34
This is actually an issue with the map (I don't remember which one) for which this error manifests. This error is rather benign and occurs in more than one map, each with a different node name. While this is low priority, I think this error should be fixed sometime.

The cause of these errors is that while CTF supports most of the nodes from MTG, it doesn't support some of the rather obscure ones like fireflies, butterflies, "apple mark" (used as a placeholder for apple regrowth, AFAIK), etc. Ideally, I'd like to perform a "validation" of sorts before exporting the map, which could maybe warn the map maker and abort the export. See #429 for more info.

**Closed** 2020-06-13 15:36 UTC
Labels: Bug / Bugfix, Low Priority :sleeping:
