### ISSUE TITLE
Show HP when you hover on teammates

### ISSUE THREAD

**Issue by Emojigit** [MT-CTF/capturetheflag#863] opened 2021-04-12 11:47 UTC
Show HP when you hover on teammates

**Comment by Emojigit** [comment] 2021-04-24 10:23
This requires a global step which may cause lags

**Comment by LoneWolfHT** [comment] 2021-04-25 13:38
You could do it by setting player infotext

**Comment by appgurueu** [comment] 2021-05-24 19:26
> You could do it by setting player infotext

But that would then apply to enemies too

**Comment by appgurueu** [comment] 2021-11-30 12:48
@savilli was this implemented?

**Comment by farooqkz** [comment] 2023-05-27 15:19
May I ask why is this feature useful?

**Comment by LoneWolfHT** [comment] 2023-06-11 18:11
It gives you exact numbers that you don't get from looking at player's HP bars. Maybe useful for medics.

I think if you enable a debug setting you can already see player HP in their infotext, so CTF's implementation would probably just be a prettier layer over that

**Comment by farooqkz** [comment] 2023-06-11 18:15
I've been medic many times in game and I would say this feature is not a big deal for a medic.

**Comment by LoneWolfHT** [comment] 2023-06-11 18:17
I will close this until someone expresses reasonable interest then

**Closed** 2023-06-11 18:17 UTC
Labels: Feature :star:, Engine change needed :steam_locomotive:, :gear: Teams

**Comment by LoneWolfHT** [comment] 2023-06-12 15:23
Aka *won't do*, can't reproduce, duplicate, or stale issue. I disagree with the wording 'not planned' that they use as the main name.
![image](https://github.com/MT-CTF/capturetheflag/assets/28972859/ed022566-1b07-43e4-b2a7-af826f7e9292)

We don't have enough trouble with organization to fret about how issues are closed though. I'd recommend you just ignore the end of the close message for now.
