### ISSUE TITLE
Players can grapple out of the map

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#586] opened 2020-04-24 02:22 UTC
Players report that they're able to grapple out of the map. This is mostly by luck, as I'm unable to reproduce this even once, both in singleplayer and on the server. I suspect this would happen more in when there's more lag.

It's better to not allow the player to even teleport if the destination is outside the map. I'll work on this.

**Comment by ClobberXD** [comment] 2020-04-24 08:34
I was thinking of the following solution:

- Raycast from destination pos to map's center.
- If any barrier nodes are encountered, the player is taken to be outside the map bounds. Disallow teleport and return hook to player's inv.

The problem here is that there is no way to identify the ind. stone barrier nodes - since the introduction of indestructible nodes, `ctf_map:ind_stone` has been aliased to `ctf_map:stone`. There's no way of telling whether or not a given ind. stone node is a part of the barrier or a part of the map itself. Stupid mistake on my part. We *could* revert this change and have a separate node as a barrier node, but we'll have to fix all the existing maps to make use of the new node.

Another idea I thought of - this is much more straight-forward. The map maker would export an extra field `barrier_r` that holds the radius of the outer barriers. This field is already in use in map_maker, but it isn't exported (probably because it was of no use to CTF). But the problem with this approach is that apart from updating the map_maker mod to export the new field, we'd have to manually calculate the radius for existing maps.

The `barrier_r` idea seems to be more viable to me. Thoughts?

**Comment by rubenwardy** [comment] 2020-04-24 13:45
How does the grapple collide with things? If it's going fast enough, it'll need to use raycast to check for collisions rather than relying on built-in

**Comment by ClobberXD** [comment] 2020-04-24 16:51
It's launched using `set_velocity`+`set_acceleration`, and then moves using `set_velocity` in a globalstep.

https://github.com/MT-CTF/shooter/blob/5238358ce5cdb5b6d76f7776accadcdeb0b145c4/shooter_hook/init.lua#L59-L85

**Comment by rubenwardy** [comment] 2020-04-25 17:47
In which case, a raycast is needed if the grappling hook goes faster than 1 nodes in a step

https://gitlab.com/rubenwardy/conquer/-/blob/master/src/ArrowEntity.lua#L100

**Comment by ClobberXD** [comment] 2020-04-26 05:57
You're right. It's also the same story with grenades, wherein it checks for the node at its pos only twice per second - if the nade is fast enough, it can completely phase through a 1-node wide floor/wall.

**Comment by LoneWolfHT** [comment] 2020-07-10 01:03
This may not be a bug now that grapples use moveresult

**Comment by LoneWolfHT** [comment] 2020-07-10 15:58
Can't reproduce at all, closing for now

**Closed by LoneWolfHT** 2020-07-10 15:58 UTC
Labels: :gear: Tools / Weapons, Bug / Bugfix, Yet Another Shooter Bug
