### ISSUE TITLE
Weapon Shortage mid game

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#93] opened 2018-01-29 02:46 UTC
Not being in the pro-section is a massive disadvantage to good but new players. Once a game has started, there are no new weapons to be found, and any crafted weapons usually end up in the pro section

**Comment by AKryukov92** [comment] 2018-01-29 05:46
What behavior do you expect from new players?

I think they should craft weapons for themselves.
Stone (on H&L or bridge), bronze (in cave) sword is good enough, if you team up with someone.

If "new but good players" will take good sword, run to enemy base and die there, it will be waste of sword.

**Comment by afshaan4** [comment] 2018-01-29 05:55
In the cave map the players spawn with a pick and that is a pretty effective weapon, though in the other maps this  might be an issue

**Comment by AKryukov92** [comment] 2018-02-04 19:58
If there will be more useful weapons but swords, then there will be no shortage midgame.
Check #70 to see proposal for crossbows.

**Comment by Gaara95** [comment] 2018-02-12 08:47
true the new players go and die at enemy base but so do the new players on the other side so its kinda equal

**Comment by afshaan4** [comment] 2018-02-12 12:39
>true the new players go and die at enemy base but so do the new players on the other side so its kinda equal

True, that's how the weapon balance equalizes after a while.

Though sometimes a match lasts long enough for both sides to make good defenses(a fortress moats and the like), and then players wander less and stay at their base as guards.

maybe the chest should refresh after a while? Like 5 to 6 minutes into the game?

**Comment by farooqkz** [comment] 2018-04-09 15:29
new but good players could go find weapons which are left somewhere in the battlefield.
Also I don't think it is hard and takes long for good players to get 1K.

**Comment by ClobberXD** [comment] 2018-04-10 07:24
> Not being in the pro-section is a massive disadvantage to good but new players
This would deter the good players from creating one too many alts.

Not being able to get a weapon from the pro-section is a part of the challenge IMO - it doesn't take long to go from 0 to 1K score. I once created an alt, killed 10-12 pros, and was able to access the pro-section within an hour. The others' mileage may vary, but not to a great extent...

**Comment by ChristianSirolli** [comment] 2018-06-21 02:31
How about the weapons (and other stuff) regenerate after the game has lasted about an 1 hour or 30 min?

**Comment by ClobberXD** [comment] 2018-06-21 05:05
This issue could also be fixed to a certain extent by increasing the pro-chest requirements, since one of the root causes of this issue is non-pros ransacking the pro-chest, leaving very few weapons to none for the pros to take.

**Comment by ClobberXD** [comment] 2018-08-26 08:10
This issue especially applies to ammo, which keeps reducing on use. If the match is long enough, there's a high chance that all ammo would be used up as time passes by... Is it a good idea to periodically respawn treasure chests?

**Comment by LoneWolfHT** [comment] 2020-09-22 15:47
Closing for now because I think the classes update fixes this

**Closed by LoneWolfHT** 2020-09-22 15:47 UTC
Labels: :gear: Tools / Weapons
