### ISSUE TITLE
Crash in crafting

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#242] opened 2018-11-14 12:23 UTC
On crafting ladder

**Comment by rubenwardy** [comment] 2018-11-14 19:43
```
2018-11-14 19:42:24: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'crafting' in callback environment_Step(): ...est/.minetest/games/capturetheflag/mods/crafting/gui.lua:88: attempt to index local 'result' (a nil value)
2018-11-14 19:42:24: ERROR[Main]: stack traceback:
2018-11-14 19:42:24: ERROR[Main]: 	...est/.minetest/games/capturetheflag/mods/crafting/gui.lua:88: in function 'make_result_selector'
2018-11-14 19:42:24: ERROR[Main]: 	...minetest/games/capturetheflag/mods/crafting/stations.lua:41: in function 'get_formspec'
2018-11-14 19:42:24: ERROR[Main]: 	...netest/.minetest/games/capturetheflag/mods/sfinv/api.lua:111: in function 'set_player_inventory_formspec'
2018-11-14 19:42:24: ERROR[Main]: 	...netest/.minetest/games/capturetheflag/mods/sfinv/api.lua:127: in function 'set_page'
2018-11-14 19:42:24: ERROR[Main]: 	...minetest/games/capturetheflag/mods/crafting/stations.lua:60: in function 'func'
2018-11-14 19:42:24: ERROR[Main]: 	...minetest/minetest_stable/bin/../builtin/common/after.lua:18: in function <...minetest/minetest_stable/bin/../builtin/common/after.lua:4>
2018-11-14 19:42:24: ERROR[Main]: 	...inetest/minetest_stable/bin/../builtin/game/register.lua:420: in function <...inetest/minetest_stable/bin/../builtin/game/register.lua:400>
```

**Comment by AKryukov92** [comment] 2018-11-16 19:46
Can't reproduce on version 696a44d3d916b8ce599866a4a0f60eae03f54119
Testing scenario:
* Start a game
* Join as red player
* Take sticks from chest
* Craft ladder

Everything is fine. Server functions as usual.

**Comment by ClobberXD** [comment] 2018-11-30 13:34
Can't reproduce on latest git of `capturetheflag` using 0.4.17.1

**Comment by AKryukov92** [comment] 2018-12-01 17:44
Version 6e8ca1505dd4d0df517193ad99eabc2a05cc247f
Tried crafting ladder with filters:
* no filter - success
* "default" - success
* "default:l" - success
* "la" (only ladder) - success
* "er" (arrows, ladder, ammo) - success

Can't reproduce with filters.

Variable "result" declared at line 88 will take nil value on access to out-of-array index i.
It should not happen because loop iterates up to minimal of values: length of array or to amount of items on the page. Thus, it can't be greater than length of array.

"amount of items on the page" might be NaN if filter excludes all available items.
`math.min(1,0/0)` returns `nan`. But in this case, loop will not iterate at all.

One possible option is to try to craft in times of serious lag. When client sends filter to server, and immediadely sends craft command before receiving filtering results.
Any idea how to reproduce lag?

**Comment by LoneWolfHT** [comment] 2018-12-01 22:56
Set it up in a local copy so that the server ignores the filter until it receives a craft or something similar?

**Comment by rubenwardy** [comment] 2018-12-02 14:40
The crash happens roughly once a day

**Comment by AKryukov92** [comment] 2018-12-02 18:04
Verbose logging PR as I promised: https://github.com/rubenwardy/crafting/pull/23

**Comment by ClobberXD** [comment] 2019-03-17 05:49
Looks like the issue is in crafting sub-module. So closing.

**Closed by ClobberXD** 2019-03-17 05:49 UTC
Labels: Unconfirmed bug
