### ISSUE TITLE
Orphaned entities at nearest mapblock origin

### ISSUE THREAD

**Issue by skittlemittle** [MT-CTF/capturetheflag#99] opened 2018-02-04 15:03 UTC
There is a bunch of floating name tags on the bridge in the "bridge" map.
They stay all through the game

![screenshot from 2018-02-04 20-22-46](https://user-images.githubusercontent.com/20749736/35778871-74e51f8a-09ea-11e8-9d38-74421d5abd76.png)

**Comment by ClobberXD** [comment] 2018-02-05 02:05
Occasionally their health seems to decrease when hit... weird!

**Comment by ClobberXD** [comment] 2018-02-06 07:53
The name-tags in the jumbled mess are generally those of players currently in-game, and not random name-tags.

**Comment by afshaan4** [comment] 2018-02-06 08:33
>The name-tags in the jumbled mess are generally those of players currently in-game, and not random name-tags.

Whoah really? Thats odd, does the players health decrease when you hit the name?

**Comment by ClobberXD** [comment] 2018-02-08 08:55
Occasionally the health gauge shows their health decreasing when hit, but that doesn't seem to happen the last couple of days.

**Comment by afshaan4** [comment] 2018-02-08 14:59
I saw them in the "two hills" map today.
I'll get a screen shot tommorow.

**Comment by mrowlbio** [comment] 2018-02-09 06:14
I got the screenshot @afshaan4  

![2018-02-08-192009_1440x900_scrot](https://user-images.githubusercontent.com/28918634/36014185-8227a3aa-0d8e-11e8-9e4f-644fb1a69848.png)

**Comment by afshaan4** [comment] 2018-02-09 06:39
Is this a bug in the CTF engine?
Coz, as seen in the screenshots it's in all the maps.

**Comment by AKryukov92** [comment] 2018-02-09 15:21
You know, I have seen a lot of people without health bars and nicknames. Those are probably theirs.
Do you see health bar above those players?

**Comment by afshaan4** [comment] 2018-02-09 16:03
Yeah in noticed that, and can confirm some players dont have name tags or health

**Comment by ClobberXD** [comment] 2018-02-12 10:06
Players without gauges and name-tags is because they wouldn't have loaded yet. It happens only when I join, or when a new match begins, and they load after a couple of seconds. The slower the internet, the more noticeable the bug is...

**Comment by ClobberXD** [comment] 2018-02-18 05:49
Saw a bunch of name-tags and a mese-sword in the caverns map at `(-1800,-1.5,0)` (the x-coord could also be non-negative - I don't remember correctly)

Also, a player's name gets added to the jumbled mess, right after a player joins, and disappears right after the player leaves.

**Comment by afshaan4** [comment] 2018-02-18 08:03
is this a bug in the ctf-pvp engine?

**Comment by ClobberXD** [comment] 2018-02-19 02:16
I just remembered - a player once showed this to me in the 2hills map (in the same place) _3 months ago_ -
 way before multiple maps came into existence!

**Comment by ClobberXD** [comment] 2018-03-09 16:32
Of late, the number of names within the garbage has decreased and instead, I'm also seeing a wooden sword among the fewer name-tags.

**Comment by ClobberXD** [comment] 2018-03-16 04:40
Update - the issue has been auto-magickally resolved in the Bridge map - no name tags whatsoever. However, @rubenwardy confirmed that the code was not updated at all in the recent weeks - strange...

**Comment by afshaan4** [comment] 2018-03-17 05:59
interesting

**Comment by ClobberXD** [comment] 2018-06-24 06:48
Duplicate of #86 
However, this should remain open and the original issue should be closed as it hasn't gathered any momentum.

**Comment by ClobberXD** [comment] 2018-11-10 11:10
I came across [this attachment bug](https://github.com/minetest/minetest/issues/7841) which is probably the reason for floating nametags, wielditems, and gauges, all of which use attachments.

**Comment by appgurueu** [comment] 2018-11-10 12:55
Hacky solution, as mentioned there, is to attach on step. Will try a PR.

**Comment by AKryukov92** [comment] 2018-11-10 14:13
I can make a PR, but I need to locally test it. Can you describe me how to reproduce this bug?

**Comment by archfan7411** [comment] 2019-02-21 02:21
I've also seen other floating entities, esp. on the Bridge map. In one round a pickaxe was visible:
![image](https://user-images.githubusercontent.com/33993466/53138797-77ce1e80-3555-11e9-8fd5-0f660275719a.png)

**Comment by ClobberXD** [comment] 2019-02-21 09:31
Yes they still do exist, albeit in much smaller numbers.

**Comment by discon-nected** [comment] 2019-03-19 22:27
We have this issue on our [King of the Hill](https://ratmix.com) server. One of the items was a mirror of the item I was wielding. If I changed items in my hand, the 'orphaned item' would also change.

**Comment by ClobberXD** [comment] 2019-03-20 01:28
Delaying the entity attachments did help, but the issue still remains, albeit to a lesser degree. We can give @appgurueu's solution (https://github.com/MT-CTF/capturetheflag/issues/99#issuecomment-437581991) a try.

**Comment by discon-nected** [comment] 2019-03-20 02:55
Looks like his solution is only for name tags, which I don't see any more. We don't use health bars, so not sure if they are still a problem.

**Comment by ClobberXD** [comment] 2019-03-20 04:54
The issue is the same for all orphaned entities - they try to attach to a non-existent player (because the player wouldn't have joined yet). Hence, this fix is equally applicable to all entities that display this behaviour. I'll give it a try and see if it works.

**Comment by discon-nected** [comment] 2019-03-20 05:00
I think the items are different. On our server, players are not given items when they join. Instead that use a kit command to get them. So the items I see were not attached to an joining player.

**Comment by ClobberXD** [comment] 2019-03-20 05:05
That's strange. Here's some explanation regarding this issue: https://github.com/minetest/minetest/issues/7841#issuecomment-437575163

**Comment by ClobberXD** [comment] 2019-03-20 06:08
In that issue, it's also stated that this bug isn't present on 5.0.0, but that doesn't seem to be the case, as I think those entities are still around in our 5.0.0 server. I'll confirm this in a bit.

**Comment by discon-nected** [comment] 2019-03-20 06:20
Maybe there was more than one reason for this. Perhaps wield3d is also causing a similar effect.

**Comment by ClobberXD** [comment] 2019-03-20 06:23
I too suspect the same. This isn't just a bug that manifests when a player joins the server. :thinking:

**Comment by discon-nected** [comment] 2019-03-20 06:26
We may know for sure if the bug no longer presents itself on our server.

**Comment by discon-nected** [comment] 2019-03-24 00:31
Haven't seen the ghost entities since removing default wield3d. Will keep an eye out...

**Comment by ClobberXD** [comment] 2019-03-24 07:51
I can confirm that this bug is no longer present on CTF 5.0.0. Closing. :tada:

**Comment by Thomas--S** [comment] 2019-03-24 18:02
Found today on the server, River valleys map:
![screenshot_20190324_185953](https://user-images.githubusercontent.com/7414098/54883597-62efee00-4e67-11e9-9352-abdc0950ec13.png)

**Comment by discon-nected** [comment] 2019-03-24 18:15
Just to clarify, I had this problem with MT5, but it seems to have disappeared after swapping wield3d with 3D Armour's wieldview. So I think it is still an MT5 issue.

**Comment by ClobberXD** [comment] 2019-03-25 01:14
It's strange to see gauges still exist in an orphaned state. Esp. since I couldn't see even one entity in the usual spots on most maps (generally along Z=0), including Bridge.

**Comment by discon-nected** [comment] 2019-04-06 02:40
I saw an orphaned nametag today on KTH. So maybe wield3d was not the culprit. Very rare to see them now though.

**Comment by ClobberXD** [comment] 2019-04-06 07:02
`wield3d` and `wieldview` have nothing to do with nametags, which belong to the `playertags` mod (or similar mods).

**Comment by discon-nected** [comment] 2019-04-06 07:06
OK. Just FYI these show up a lot on the Frost Factions server.

**Comment by ClobberXD** [comment] 2019-07-30 04:25
This is a bug in MT, and has been fixed by https://github.com/minetest/minetest/pull/8701 :tada:

**Closed** 2021-11-30 01:16 UTC
Labels: Bug / Bugfix, Medium Priority

**Comment by appgurueu** [comment] 2021-11-30 12:51
Forgotten to close (see ClobberXD's comment).
