### ISSUE TITLE
Crashes server if using the --terminal option and chat

### ISSUE THREAD

**Issue by grantcarthew** [MT-CTF/capturetheflag#623] opened 2020-05-08 02:16 UTC
Hi,
I have raised this issue with the `afkkick` mod however it is also an issue here.

Rather than duplication the details, I'll reference the issue in the `afkkick` mod.

https://github.com/GunshipPenguin/afkkick/issues/4

**Comment by ClobberXD** [comment] 2020-05-08 05:49
This issue indeed seems to be caused by `playerName` being `nil`. A simple if-playerName-then check ought to fix this crash. OTOH, it seems pretty inconsistent of Minetest to pass a nil value here - I'd expect the value of the setting `name` (this is the name the terminal chat functions under) to be passed in.

**Comment by grantcarthew** [comment] 2020-05-08 05:55
Does this mod get synced with the source mod at @GunshipPenguin?

**Comment by ClobberXD** [comment] 2020-05-08 06:11
AFAIK, no. There doesn't seem to be any new commits, apart from https://github.com/GunshipPenguin/afkkick/pull/3 which was backported from CTF. CTF's version, however, is a little more active, and has gone through the following changes:

- [Before modpack re-organisation](https://github.com/MT-CTF/capturetheflag/commits/v1.17.0/mods/afkkick)
- [After modpack re-organisation](https://github.com/MT-CTF/capturetheflag/commits/master/mods/other/afkkick)

**Comment by grantcarthew** [comment] 2020-05-08 06:19
Ok.
Seems a shame to have duplicates.
I found this today: https://github.com/minetest-mods/
Instructions here: http://minetest-mods.github.io/

Maybe it is worth getting it supported under there? Then import the module into CTF? Just a suggestion.

**Comment by ClobberXD** [comment] 2020-05-08 06:22
Thanks for reporting this crash. Fixed in 3de7c433.

**Closed by ClobberXD** 2020-05-08 06:22 UTC
